Actividad Tema_10
UnirCs/BBDD-PER8263-2324 pull request #74
Opened 2023-12-25 20:16 UTC by JMPinillos

Buenas noches profe, realizo la entrega de la actividad del tema 10 con los siguientes archivos:

- Entrega_ES.md.
- Consultas Elasticsearch.postman_collection.json

Felices fiestas.

2023-12-26 23:33 UTC, UnirCs commented on Tema_10/Elasticsearch/Readme.md
No modifiques mis ficheros please!

2023-12-26 23:34 UTC, UnirCs commented on Tema_10/Elasticsearch/elasticsearch-operations-postman/EmployeesV2_raw.json
Mete esto en tu carpeta please!

2023-12-26 23:34 UTC, UnirCs commented on Tema_10/Elasticsearch/elasticsearch-operations-postman/Employees_raw.json
Mete esto en tu carpeta please!

2023-12-26 23:34 UTC, UnirCs commented on Tema_10/Elasticsearch/elasticsearch-operations-postman/Operaciones en Elasticsearch.postman_collection.json
Mete esto en tu carpeta please!

2023-12-26 23:34 UTC, UnirCs commented on Tema_10/Elasticsearch/elasticsearch-operations-postman/Readme.md
Mete esto en tu carpeta please!

2023-12-26 23:34 UTC, UnirCs commented on Tema_10/Readme.md
No modifiques mi fichero

2023-12-26 23:35 UTC, UnirCs requested changes
El ejercicio está bien José Manuel, pero tocas mis archivos y añades otros en la raíz. Déjalo en tu carpeta por favor.

2023-12-27 07:14 UTC, JMPinillos commented on Tema_10/Elasticsearch/Readme.md
Hecho, sorry!

2023-12-27 07:14 UTC, JMPinillos commented on Tema_10/Elasticsearch/elasticsearch-operations-postman/EmployeesV2_raw.json
Hecho, sorry!

2023-12-27 07:15 UTC, JMPinillos commented on Tema_10/Elasticsearch/elasticsearch-operations-postman/Operaciones en Elasticsearch.postman_collection.json
Hecho, sorry!

2023-12-27 07:15 UTC, JMPinillos commented on Tema_10/Elasticsearch/elasticsearch-operations-postman/Readme.md
Hecho, sorry!

2023-12-27 07:15 UTC, JMPinillos commented on Tema_10/Readme.md
Hecho, sorry!

2023-12-27 07:18 UTC, JMPinillos commented
Buenos días profe, he realizado los cambios y un _commit_, no se si con eso servirá para que se adjunten los cambios en el _Pull request_ actual.
Si tengo que realizarlo de otra manera ya me dirás. 
Gracias

2023-12-27 07:24 UTC, UnirCs approved these changes
OK!

2023-12-27 07:24 UTC, merged